# TPZASM: TDL ZASM / PSA PASM compatible assembler - REUSE.toml
# Copyright (c) 2026 Jeffrey H. Johnson <johnsonjh.dev@gmail.com>
# SPDX-License-Identifier: MIT-0
# scspell-id: 7946bedc-6335-11f1-a03a-246e96298730

version = 1
SPDX-PackageName = "tpzasm"
SPDX-PackageSupplier = "Jeffrey H. Johnson <johnsonjh.dev@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/johnsonjh/tpzasm"

[[annotations]]
path = "tests/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Jeffrey H. Johnson <johnsonjh.dev@gmail.com>"
SPDX-License-Identifier = "MIT-0"

[[annotations]]
path = "tools/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Jeffrey H. Johnson <johnsonjh.dev@gmail.com>"
SPDX-License-Identifier = "MIT-0"

[[annotations]]
path = "docs/re/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Jeffrey H. Johnson <johnsonjh.dev@gmail.com>"
SPDX-License-Identifier = "MIT-0"

[[annotations]]
path = "docs/Z80_Assm.zip"
precedence = "aggregate"
SPDX-FileCopyrightText = "2009 R. Roger Breton"
SPDX-License-Identifier = "LicenseRef-ZALUT"

[[annotations]]
path = "docs/TDL_ZASM*.pdf"
precedence = "aggregate"
SPDX-FileCopyrightText = "1976, 1977 Technical Design Labs, Inc."
SPDX-License-Identifier = "LicenseRef-TDL"

[[annotations]]
path = "tests/zapple.asm"
precedence = "aggregate"
SPDX-FileCopyrightText = "1976 Technical Design Labs, Inc."
SPDX-License-Identifier = "LicenseRef-TDL"

[[annotations]]
path = "tests/dis.asm"
precedence = "aggregate"
SPDX-FileCopyrightText = "1979 Tim Burke"
SPDX-License-Identifier = "LicenseRef-DIS"

[[annotations]]
path = "orig/zasm.com"
precedence = "aggregate"
SPDX-FileCopyrightText = "1976, 1977 Technical Design Labs, Inc."
SPDX-License-Identifier = "LicenseRef-TDL"

[[annotations]]
path = "docs/PSA_PASM.pdf"
precedence = "aggregate"
SPDX-FileCopyrightText = "1980 Phoenix Software Associates Ltd."
SPDX-License-Identifier = "LicenseRef-PSA"

[[annotations]]
path = "orig/pasm.com"
precedence = "aggregate"
SPDX-FileCopyrightText = "1980 Phoenix Software Associates Ltd."
SPDX-License-Identifier = "LicenseRef-PSA"

[[annotations]]
path = "orig/pasm2.com"
precedence = "aggregate"
SPDX-FileCopyrightText = "1981 Phoenix Software Associates Ltd."
SPDX-License-Identifier = "LicenseRef-PSA"

[[annotations]]
path = "orig/hexcom.com"
precedence = "aggregate"
SPDX-FileCopyrightText = "1982 Digital Research"
SPDX-License-Identifier = "LicenseRef-DRDOS"

[[annotations]]
path = "bindist/*"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Jeffrey H. Johnson <johnsonjh.dev@gmail.com>"
SPDX-License-Identifier = "MIT-0"

[[annotations]]
path = ".utils/lharc.ttp"
precedence = "aggregate"
SPDX-FileCopyrightText = "Yoshizaki, 1988-1989, Grunenberg, Mandel, 1994, Haun, 1996/97"
SPDX-License-Identifier = "LicenseRef-LHA"
